package com.company.expensetracker;

import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import java.io.IOException;

public class SignUp extends javax.swing.JFrame {
    //makes fields empty after a sign up attempt
    private void resetFields(){
            nameInput.setText("");
            passwordInput.setText("");
            budgetInput.setText("");
    }
    
    //checks if the budget string is a proper integer
    private boolean validateBudget(String budget){
        try{
            int validatedBudget = Integer.parseInt(budget);
            return true;
        }catch(Exception error){
            resetFields();
            return false;
        }
    }
    
    //check password format
    private boolean validatePassword(String password){
        //^ start of the string, $ end of the string
        //(?=.*[A-Z]) at least one uppercase, (?=.*[a-z]) at least one lowercase, (?=.*\\d) at least one digit , 
        //(?=.*[@$!%*#&]) at least one of these symbols @$!%*#&, 
        //[A-Za-z\\d@$!%*?&]+ checks if the whole password has allowed values (which are uppercase, lowercase,numbers, and some symbols)
        if(password.length() >= 8 && password.matches("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]+$")){
            return true;
        }
        return false;
    }
    
    private boolean validateInputs(String username, String password, String budget){
        boolean isUsernameCorrect = username.length()>=3;
        boolean isBudgetCorrect = validateBudget(budget);
        boolean isPasswordCorrect = validatePassword(password);
   

        return (isUsernameCorrect && isBudgetCorrect && isPasswordCorrect);
    }
    
    //writes the new data in the files
    private void writeInDB(String username, String password, int budget){
        try{
            FileWriter usernameWriter = new FileWriter("C:\\Users\\User\\Documents\\NetBeansProjects\\ExpenseTracker\\src\\main\\java\\com\\company\\expensetracker\\usernameDB.txt");
            FileWriter passwordWriter = new FileWriter("C:\\Users\\User\\Documents\\NetBeansProjects\\ExpenseTracker\\src\\main\\java\\com\\company\\expensetracker\\passwordDB.txt");
            FileWriter budgetWriter = new FileWriter("C:\\Users\\User\\Documents\\NetBeansProjects\\ExpenseTracker\\src\\main\\java\\com\\company\\expensetracker\\budgetDB.txt");

            usernameWriter.write(username + ";\n");
            usernameWriter.close();
            
            passwordWriter.write(password + ";\n");
            passwordWriter.close();
            
            budgetWriter.write(budget + ";");
            budgetWriter.close();
            
            resetFields();
        }
      catch(IOException io){
                     System.out.println("There was an error trying to write in the database!");
      }
}
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainContainer = new javax.swing.JPanel();
        passwordInput = new javax.swing.JPasswordField();
        nameInput = new javax.swing.JTextField();
        unitSelector = new javax.swing.JComboBox<>();
        budgetInput = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        signUpBTN = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        psswLabel = new javax.swing.JLabel();
        budgetLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Tracker");
        setBackground(new java.awt.Color(241, 241, 241));
        setBounds(new java.awt.Rectangle(0, 0, 1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("SignUpFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        mainPanel.setBackground(new java.awt.Color(241, 241, 241));
        mainPanel.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledBackground"));

        mainContainer.setBackground(new java.awt.Color(217, 217, 217));
        mainContainer.setPreferredSize(new java.awt.Dimension(522, 599));

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });

        unitSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "ALL", "EUR" }));

        logoLabel.setFont(new java.awt.Font("Georgia", 3, 72)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(0, 0, 102));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("ET");

        signUpBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpBTN.setText("SIGN UP");
        signUpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBTNActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("NAME (3 or more characters):");

        psswLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        psswLabel.setForeground(new java.awt.Color(51, 51, 51));
        psswLabel.setText("PASSWORD:");

        budgetLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        budgetLabel.setForeground(new java.awt.Color(51, 51, 51));
        budgetLabel.setText("BUDGET (whole number):");

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(budgetLabel))
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(psswLabel))
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(signUpBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordInput)
                            .addComponent(nameInput)
                            .addGroup(mainContainerLayout.createSequentialGroup()
                                .addComponent(budgetInput, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unitSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainContainerLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(nameLabel)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(psswLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(budgetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(signUpBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void signUpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBTNActionPerformed
        // TODO add your handling code here:
       final String userName = nameInput.getText();
       final String userPassword = String.valueOf(passwordInput.getPassword());//turns char[] into String :))))))))))))
       final String userBudget = budgetInput.getText();
       final String currencyType = unitSelector.getSelectedItem().toString();
       
       
       if(validateInputs(userName, userPassword, userBudget)){
            writeInDB(userName, userPassword, Integer.parseInt(userBudget));
            System.out.println("Written in db");
       }else{
                  resetFields();
                  errorLabel.setText("The password must be at least 8 characters long, contain uppercase and lowercase letters, a number and a symbol!");
       }
    }//GEN-LAST:event_signUpBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budgetInput;
    private javax.swing.JLabel budgetLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel psswLabel;
    private javax.swing.JButton signUpBTN;
    private javax.swing.JComboBox<String> unitSelector;
    // End of variables declaration//GEN-END:variables
}
